# Generated by Django 2.0.7 on 2018-07-24 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180724_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 19, 34, 48, 890059, tzinfo=utc), null=True),
        ),
    ]
