# Generated by Django 2.0.7 on 2018-07-24 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180724_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 19, 40, 28, 999491, tzinfo=utc), null=True),
        ),
    ]
