# Generated by Django 2.0.7 on 2018-07-24 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180724_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 24, 20, 3, 33, 180646, tzinfo=utc), null=True),
        ),
    ]
